image:
  file: .gitpod.Dockerfile

tasks:
  - init: echo "Replace me with a build script for the project."
    command: odoo -r gitpod --addons-path=/workspace -d template1 -i base -D /workspace/.odoo
