image:
  file: .gitpod.Dockerfile

# exposed ports
ports:
- port: 5432 # PostgreSQL
  onOpen: ignore
- port: 8069 # preview on browser
  onOpen: open-browser

vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==`

tasks:
  - init: |
      ./odoo-install.sh
    command: |
      cd odoo && ./odoo-bin -w odoo11 -r odoo11 --addons-path=./addons --db_host 127.0.0.1
  - command: gp await-port 8069 && gp preview "$(gp url 8069)/web/login"

# P.S. You should remove ":433" from the url when running the web preview.

# Create a database
#CREATE DATABASE odoo11_db WITH OWNER odoo11;
#GRANT ALL PRIVILEGES ON DATABASE odoo11_db TO odoo11;

# Run with database:
#./odoo-bin -w odoo11 -r odoo11 -d odoo11_db --addons-path=./addons --db_host 127.0.0.1

# Run with different PostgreSQL port:
#./odoo-bin -w odoo11 -r odoo11 --addons-path=./addons --db_host 127.0.0.1 --db_port 5433

# Run and init a database:
#./odoo-bin -w odoo11 -r odoo11 -d odoo11_db --addons-path=./addons --db_host 127.0.0.1 -i base
