tasks:
  - init: echo "Replace me with a build script for the project."
    command: odoo -r gitpod --addons-path=/workspace -d template1 -i base -D /workspace/.odoo
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==`