image:
  file: .gitpod.Dockerfile

# exposed ports
ports:
- port: 5432 # PostgreSQL
  onOpen: ignore
- port: 8069 # preview
  onOpen: open-preview

tasks:
  - init: ./odoo-install.sh
    command: gp await-port 8069 && gp preview $(gp url 8069)

vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==`
