image:
  file: .gitpod.Dockerfile

# exposed ports
ports:
- port: 5432 # PostgreSQL
  onOpen: ignore
- port: 8069 # preview
  onOpen: open-preview

vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==`

tasks:
  - init: |
      sudo sed 's/peer/md5/g' /etc/postgresql/12/main/pg_hba.conf
      sleep 1
      pg_ctl reload
      sleep 1
      ./odoo-install.sh
      cd odoo
      ./odoo-bin -w odoo11 -r odoo11 --addons-path=./addons --db_host 127.0.0.1
    command: gp await-port 8069 && gp preview $(gp url 8069)

#sudo apt install wget curl ca-certificates
#wget -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
#sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
#sudo apt update
#sudo apt-get install postgresql-9.6 postgresql-contrib-9.6 -y
#pg_ctl stop
#sudo pg_ctlcluster 12 main stop
#sudo pg_ctlcluster 9.6 main start
#you can then login to psql with: "sudo su - postgres" then "psql" then create DBs...
#make port 5433 public, then you'll need to run odoo with "--db_port 5433"
